[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
picassol = "5rV2CJ8bYV4qEt8qcmhZ1Ty3o6eM7K1LAJDDFipPNyx2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/devtex/.config/solana/ey.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
